/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiSideDrawer {
        "open": boolean;
        "openDrawer": () => Promise<void>;
        "title": string;
    }
    interface UiStockPrice {
    }
}
declare global {
    interface HTMLUiSideDrawerElement extends Components.UiSideDrawer, HTMLStencilElement {
    }
    var HTMLUiSideDrawerElement: {
        prototype: HTMLUiSideDrawerElement;
        new (): HTMLUiSideDrawerElement;
    };
    interface HTMLUiStockPriceElement extends Components.UiStockPrice, HTMLStencilElement {
    }
    var HTMLUiStockPriceElement: {
        prototype: HTMLUiStockPriceElement;
        new (): HTMLUiStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "ui-side-drawer": HTMLUiSideDrawerElement;
        "ui-stock-price": HTMLUiStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface UiSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface UiStockPrice {
    }
    interface IntrinsicElements {
        "ui-side-drawer": UiSideDrawer;
        "ui-stock-price": UiStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-side-drawer": LocalJSX.UiSideDrawer & JSXBase.HTMLAttributes<HTMLUiSideDrawerElement>;
            "ui-stock-price": LocalJSX.UiStockPrice & JSXBase.HTMLAttributes<HTMLUiStockPriceElement>;
        }
    }
}
